cifsd-team/ksmbd-tools

cifsd/ipc.c, include/cifsdtools.h, include/linux/cifsd_server.h, lib/config_parser.c
=> cifsd-tools: add deadtime parameter support

cifsd/cifsd.c
Add an optional optarg to no_detach:
- in default (current) no-detach mode we do setsid()
- in new additional no-deatch mode we don't do setsid()
=> cifsd-tools: extend no-detach mode

cifsd/ipc.c
Signed-off-by: Gibeom Kim <gibeomii.kim@samsung.com>
=> cifsd-tools: add one extra byte to iface list

cifsadmin/cifsadmin.c, cifsadmin/user_admin.c, cifsd/cifsd.c, cifsd/ipc.c, cifsd/rpc_srvsvc.c, include/cifsdtools.h, lib/cifsdtools.c, lib/config_parser.c
=> cifsd-tools: ss

README
=> cifsd: fix typo in README

include/linux/cifsd_server.h, lib/management/share.c
=> cifsd-tools: add streams parameter support

cifsshareadd/share_admin.c, cifsuseradd/user_admin.c
=> cifsd-tools: add missing parameter

cifsshareadd/cifsshareadd.c
=> cifsd: fix wrong smb.conf location option

configure.ac
=> cifsd-tools: add version generation script

configure.ac
=> cifsd-tools: release v2.0.3 version

configure.ac
=> cifsd-tools: release cifsd-tools 2.0.4 version

README
=> smbd-tools: fix wrong smbd name in README

configure.ac
=> smbd-tools: release v3.0.1 version

configure.ac
=> ksmbd-tools: release 3.1.0 version

addshare/addshare.c, addshare/share_admin.h, adduser/adduser.c, adduser/user_admin.c, adduser/user_admin.h, include/config_parser.h, include/ipc.h, include/ksmbdtools.h, include/linux/ksmbd_server.h, include/management/session.h, include/management/share.h, include/management/tree_conn.h, include/management/user.h, include/rpc.h, include/rpc_srvsvc.h, include/rpc_wkssvc.h, include/worker.h, lib/config_parser.c, lib/ksmbdtools.c, lib/management/session.c, lib/management/share.c, lib/management/tree_conn.c, lib/management/user.c, mountd/ipc.c, mountd/mountd.c, mountd/rpc.c, mountd/rpc_srvsvc.c, mountd/rpc_wkssvc.c, mountd/worker.c
=> ksmbd-tools: replace usmbd prefix with ksmbd prefix

README
=> ksmbd-tools: update how to restart ksmbd in README file

configure.ac
=> ksmbd-tools: release 3.2.0 version

configure.ac
=> ksmbd-tools: release 3.2.1 version

Documentation/configuration.txt, include/ksmbdtools.h, include/linux/ksmbd_server.h, lib/config_parser.c, mountd/ipc.c
=> ksmbd-tools: add share:fake_fscaps parameter

lib/management/share.c
=> ksmbd-tools: enable oplocks by default

configure.ac
=> ksmbd-tools: release 3.2.2 version

README
=> ksmbd-tools: update README

configure.ac, mountd/rpc.c
=> ksmbd-tools: add missing return statement

README
=> ksmbd-tools: describe how to shutdown cifsd in README

README
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>
=> ksmbd-tools: update cifsd-tools leftover

include/version.h
Major changes are:
- Add samr and lsarpc RPC support.
- Generate subauth values for domain.
- Add Kerberos support
=> ksmbd-tools: release 3.3.0 version

include/version.h
The major change are:
- Fix memleak and invalid memory write issue.
=> ksmbd-tools: release 3.3.3 version

include/linux/ksmbd_server.h
remove ____ksmbd_align in ksmbd_server.h.
=> ksmbd-tools: remove ____ksmbd_align in ksmbd_server.h
