cifsd/cifsd.c
If manager process is not a process group leader (which can
happen in no-detach mode) then make ourselves one.
Signed-off-by: Haythem Zidi <zidihaythem@gmail.com>
=> cifsd-tools: call setsid() in no-detach mode

lib/management/user.c
If cifsdpwd.db is corrupted or old one is used, password hash size could
be smaller than CIFSD_REQ_MAX_HASH_SZ - 2(16). It cause null pointer dereferencing
issue.
See : memcpy(p21, user_passkey(sess->user), CIFS_NTHASH_SIZE); in auth.c
=> cifsd-tools: password hash size should be 16

lib/management/user.c
This reverts commit dac42869be0c013c75c279a7063583665f46431c.
=> Revert "cifsd-tools: password hash size should be 16"

cifsd/ipc.c
=> cifsd-tools: always have at least 1 byte as iface payload

cifsd/rpc.c, cifsd/rpc_wkssvc.c
=> cifsd-tools: always parse req_hdr for DCERPC_PTYPE_RPC_REQUEST

cifsd/cifsd.c, cifsd/ipc.c, include/ipc.h
Do not loop in cifsd waiting for user to kill the manager process,
but terminate it automatically on any IPC error.
$ ./cifsd/cifsd -n
[cifsd-worker/3300]: INFO: share exists ipc$
[cifsd-worker/3300]: ERROR: Recv() error Invalid input data or parameter [-7]
[cifsd-manager/3281]: ERROR: WARNING: child process exited abnormally: 3300
[cifsd-manager/3281]: ERROR: Fatal IPC error. Terminating. Check dmesg.
[cifsd-manager/3281]: ERROR: can't execute kill 3300: No such process
[cifsd-manager/3281]: INFO: Exiting. Bye!
$ dmesg | tail -1
[ 1714.910124] kcifsd: cifsd_ipc_validate_version:49: Daemon and kernel module version mismatch. cifsd: 1, kernel module: 3. User-space cifsd should terminate.
=> cifsd-tools: fix for a problem which does not exist

cifsd/cifsd.c
Set `nochdir' flag for daemon().
=> cifsd-tools: do not switch pwd of daemon-ized process

lib/config_parser.c
=> cifsd-tools: enable tbuf and rbuf caching by default

configure.ac
1. merged smb direct bug fix patches into cifsd.
2. merged fix-warning-from-static analyzer patches into cifsd.
3. merged fix-warning-from-static analyzer patches into cifsd-tools.
=> cifsd-tools: increase cifsd micro version(v2.0.0 => v2.0.1)

cifsshareadd/Makefile.am, cifsuseradd/Makefile.am
Signed-off-by: Andy Walsh <andy.walsh44@gmail.com>
=> cifsd-tools: remove unneeded libnl for cifsuseradd and cifsshareadd

cifsd/ipc.c
msg_sz is size_t, not unsigned long.
Fixes warning under 32-bit. Discovered with -Wformat=2
Signed-off-by: Rosen Penev <rosenp@gmail.com>
=> cifsd-tools: Fix incorrect format

lib/config_parser.c
=> ksmbd-tools: disable tbuf and rbuf caching by default

lib/config_parser.c
This reverts commit 9f4f84f5ee4b115ba3235149c1bac8e24c9ec490.
=> Revert "ksmbd-tools: disable tbuf and rbuf caching by default"

mountd/ipc.c
Signed-off-by: Fredrik Ternerot <fredrikt@axis.com>
=> ksmbd-tools: fix minlen for KSMBD_EVENT_SHUTTING_DOWN

lib/management/session.c, lib/management/tree_conn.c
Release user related to connection when the connection is removed from
session. Previously the user was not released when session was killed or
when a session for the user already existed.
Signed-off-by: Fredrik Ternerot <fredrikt@axis.com>
=> ksmbd-tools: release user when connection is removed

include/ksmbdtools.h, include/management/share.h, include/management/user.h, lib/management/share.c, lib/management/user.c, mountd/ipc.c, mountd/mountd.c
When SIGHUP is received, reload config before next ipc event is handled
instead of after. This makes sure that no more clients could connect
with the old configuration (e.g. an old password) after SIGHUP has been
sent.
When reloading config, remove existing configuration structures before
adding new. Previously, existing shares were not updated and
shares/users that no longer exist in config files were not removed.
Signed-off-by: Fredrik Ternerot <fredrikt@axis.com>
=> ksmbd-tools: improve configuration reload on SIGHUP

configure.ac
Major changes are:
- remove handling of SIGSEGV signal.
- add shutdown description.
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>
=> ksmbd-tools: release 3.2.5 version

Makefile.am, README, configure.ac, control/Makefile.am, control/control.c
This patch add ksmbd.control util. It support the following functions.
- Shutdown(kill) ksmbd daemon by "ksmbd.control -s" command.
- Enable/Disable debug prints as per ksmbd component by "ksmbd.control
-d "all" or -d "smb" command.
- Show ksmbd version by "ksmbd.control -c" command.
Cc: Fredrik Ternerot <fredrikt@axis.com>
=> ksmbd-tools: add ksmbd.control util

include/rpc.h, mountd/rpc.c, mountd/rpc_lsarpc.c, mountd/rpc_samr.c, mountd/rpc_srvsvc.c, mountd/rpc_wkssvc.c
Instead of adding max_len and actual_len arguments in
ndr_write_vstring(), declare ndr_write_lsa_string_large() and
ndr_write_string().
Cc: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
Cc: Martin Blumenstingl <martin.blumenstingl@googlemail.com>
=> ksmbd-tools: reorganize ndr write string functions

lib/management/user.c
Remove unneeded g_strdup() in usm_add_subauth_global_conf().
Signed-off-by: Sebastian Gottschall <s.gottschall@dd-wrt.com>
=> ksmbd-tools: fix memleak in usm_add_subauth_global_conf()

include/version.h
Major changes are:
- add "vfs objects = acl_xattr" parameter in configuration.
- fix wrong group domain name in lsarpc response.
- set to SID_TYPE_UNKNOWN if there is no domain sid in server.
=> ksmbd-tools: release 3.3.4 version

include/version.h
Major changes are:
- disable symlink by default.
- remove smack inherit leftovers.
- Enable guest access on IPC$ share by default.
=> ksmbd-tools: release 3.3.8 version
